<?php
/** @var \Magento\Framework\View\Element\Template $block */
$order = $block->getOrder();
$collectionDate = $order->getClickCollectDate();

if ($order->getShippingMethod() === 'clickcollect_clickcollect' && $collectionDate): ?>
	<div class="box box-order-collection-date">
		<div class="box-title">
			<strong><?= $block->escapeHtml(__('Collection Date')) ?></strong>
		</div>
		<div class="box-content">
			<?= $block->escapeHtml(__('Your order will be available for collection on %1', $collectionDate)) ?>
		</div>
	</div>
<?php endif; ?>